#!/usr/bin/env bash
# gen-router.sh [--check] -- regenerate the GENERATED:router block in memory/index.md from
# each note's leading frontmatter (keywords / related / description). With --check, exit
# nonzero on drift and write nothing. Runs in the current project.
set -euo pipefail

CHECK=0
[ "${1:-}" = "--check" ] && CHECK=1

INDEX="memory/index.md"
VAULT="memory"
BEGIN="<!-- GENERATED:router -->"
END="<!-- /GENERATED:router -->"

[ -f "$INDEX" ] || { echo "gen-router: $INDEX not found" >&2; exit 1; }

extract_fm() {
  awk 'NR==1 && $0!="---"{exit} NR==1{next} /^---[[:space:]]*$/{exit} {print}' "$1"
}

build() {
  printf '%s\n' "$BEGIN"
  printf '%s\n' "<!-- regenerated by gen-router.sh; do not hand-edit inside these markers -->"
  find "$VAULT" -name '*.md' ! -name 'index.md' 2>/dev/null | LC_ALL=C sort | while IFS= read -r note; do
    fm="$(extract_fm "$note")"
    kw="$(printf '%s\n' "$fm" | sed -n 's/^keywords:[[:space:]]*//p' | head -1)"
    desc="$(printf '%s\n' "$fm" | sed -n 's/^description:[[:space:]]*//p' | head -1)"
    relpath="${note#"$VAULT"/}"
    line="- [[${relpath%.md}]]"
    [ -n "$kw" ] && line="$line -- keywords: $kw"
    [ -n "$desc" ] && line="$line -- $desc"
    printf '%s\n' "$line"
  done
  printf '%s\n' "$END"
}

nbfile="$(mktemp)"
trap 'rm -f "$nbfile" "${curfile:-}" "${tmp:-}"' EXIT
build > "$nbfile"

if [ "$CHECK" -eq 1 ]; then
  curfile="$(mktemp)"
  awk -v b="$BEGIN" -v e="$END" '$0==b{f=1} f{print} $0==e{f=0}' "$INDEX" > "$curfile"
  if diff -q "$nbfile" "$curfile" >/dev/null 2>&1; then
    echo "gen-router: router up to date" >&2
    exit 0
  fi
  echo "gen-router: DRIFT -- router block is stale; run gen-router.sh" >&2
  exit 1
fi

# Confirm markers exist before rewriting.
if ! grep -qF "$BEGIN" "$INDEX" || ! grep -qF "$END" "$INDEX"; then
  echo "gen-router: markers not found in $INDEX" >&2
  exit 1
fi

tmp="$(mktemp)"
awk -v b="$BEGIN" -v e="$END" -v nb="$nbfile" '
  $0==b { while ((getline line < nb) > 0) print line; close(nb); skip=1; next }
  $0==e { skip=0; next }
  skip { next }
  { print }
' "$INDEX" > "$tmp"
mv "$tmp" "$INDEX"
echo "gen-router: router regenerated in $INDEX" >&2
