#!/usr/bin/env bash
# gen-router.sh [--check] -- regenerate the GENERATED:router block in memory/index.md from
# each note's leading frontmatter (keywords / related / description). With --check, exit
# nonzero on drift and write nothing. Runs in the current project.
set -euo pipefail

CHECK=0
[ "${1:-}" = "--check" ] && CHECK=1

CONFIG="config/sefi.config.yml"

cfg_get() {
  # cfg_get <key> <default> -- read a leaf key's scalar from CONFIG. Honors
  # memory.vault_dir so the router is generated wherever the vault actually lives.
  local key="$1" default="$2" val=""
  if [ -f "$CONFIG" ]; then
    val="$(sed -n "s/^[[:space:]]*$key:[[:space:]]*\([^[:space:]#]*\).*/\1/p" "$CONFIG" | head -1)"
  fi
  printf '%s' "${val:-$default}"
}

VAULT="$(cfg_get vault_dir memory)"
INDEX="$VAULT/index.md"
BEGIN="<!-- GENERATED:router -->"
END="<!-- /GENERATED:router -->"

[ -f "$INDEX" ] || { echo "gen-router: $INDEX not found" >&2; exit 1; }

extract_fm() {
  awk 'NR==1 && $0!="---"{exit} NR==1{next} /^---[[:space:]]*$/{exit} {print}' "$1"
}

list_notes() {
  # Durability order, NOT byte order: decisions -> entities -> projects -> other -> daily
  # LAST. inject-memory.sh injects only the first ~16 router lines (head -n 40, then a
  # char cap), so whatever sorts last is what gets truncated. A plain LC_ALL=C sort put
  # daily/ first, which meant that past ~16 notes the injected router was 100% trace notes
  # and decisions/ never appeared at all (2026-07-16 audit, gap 5.1). Truncation must drop
  # trace, never decisions. Within each group, LC_ALL=C sort keeps output deterministic.
  local d
  for d in decisions entities projects; do
    if [ -d "$VAULT/$d" ]; then
      find "$VAULT/$d" -name '*.md' 2>/dev/null | LC_ALL=C sort
    fi
  done
  # Any note outside the four known folders (vault root or a custom subfolder).
  find "$VAULT" -name '*.md' ! -name 'index.md' 2>/dev/null \
    | grep -v -E "^$VAULT/(decisions|entities|projects|daily)/" \
    | LC_ALL=C sort || true
  if [ -d "$VAULT/daily" ]; then
    find "$VAULT/daily" -name '*.md' 2>/dev/null | LC_ALL=C sort
  fi
  return 0
}

build() {
  printf '%s\n' "$BEGIN"
  printf '%s\n' "<!-- regenerated by gen-router.sh; do not hand-edit inside these markers -->"
  list_notes | while IFS= read -r note; do
    fm="$(extract_fm "$note")"
    kw="$(printf '%s\n' "$fm" | sed -n 's/^keywords:[[:space:]]*//p' | head -1)"
    desc="$(printf '%s\n' "$fm" | sed -n 's/^description:[[:space:]]*//p' | head -1)"
    relpath="${note#"$VAULT"/}"
    line="- [[${relpath%.md}]]"
    [ -n "$kw" ] && line="$line -- keywords: $kw"
    [ -n "$desc" ] && line="$line -- $desc"
    printf '%s\n' "$line"
  done
  printf '%s\n' "$END"
}

nbfile="$(mktemp)"
trap 'rm -f "$nbfile" "${curfile:-}" "${tmp:-}"' EXIT
build > "$nbfile"

if [ "$CHECK" -eq 1 ]; then
  curfile="$(mktemp)"
  awk -v b="$BEGIN" -v e="$END" '$0==b{f=1} f{print} $0==e{f=0}' "$INDEX" > "$curfile"
  if diff -q "$nbfile" "$curfile" >/dev/null 2>&1; then
    echo "gen-router: router up to date" >&2
    exit 0
  fi
  echo "gen-router: DRIFT -- router block is stale; run gen-router.sh" >&2
  exit 1
fi

# Confirm markers exist before rewriting.
if ! grep -qF "$BEGIN" "$INDEX" || ! grep -qF "$END" "$INDEX"; then
  echo "gen-router: markers not found in $INDEX" >&2
  exit 1
fi

tmp="$(mktemp)"
awk -v b="$BEGIN" -v e="$END" -v nb="$nbfile" '
  $0==b { while ((getline line < nb) > 0) print line; close(nb); skip=1; next }
  $0==e { skip=0; next }
  skip { next }
  { print }
' "$INDEX" > "$tmp"
mv "$tmp" "$INDEX"
echo "gen-router: router regenerated in $INDEX" >&2
